spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/fecApp
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080

twilio:
  wppKeys:
    ACCOUNT_SID:
    AUTH_TOKEN:
  wppNumber: whatsapp:+5511993449319
